### ISSUE TITLE
TDL-5: add pdf generation

### ISSUE THREAD

**Issue by Sergeyingit** [Sergeyingit/todolist#11]
Acceptance criteria:

    generation pdf on user page

**Comment by DevPJ9** [comment]
Hello, @Sergeyingit I would like to contribute. Can you please provide some more info on the task?

**Comment by Sergeyingit** [comment]
> Hello, @Sergeyingit I would like to contribute. Can you please provide some more info on the task?

Hi.
Thank you for your interest in my project, but this is just my educational project. I don't plan to develop it further, I just try some things.
I did this task myself.
Just a link generates a simple file for the user, without saving to disk.

**Comment by Sergeyingit** [comment]
https://github.com/Sergeyingit/todolist/pull/12
